model_list:

  - model_name: Nemotron 3 Super
    litellm_params:
      model: nvidia/nemotron-3-super-120b-a12b
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        

  - model_name: Nemotron 3.1 Ultra
    litellm_params:
      model: nvidia/llama-3.1-nemotron-ultra-253b-v1
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        
        
  - model_name: Nemotron 4 Instruct
    litellm_params:
      model: nvidia/nemotron-4-340b-instruct
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        

  - model_name: Step 3.5 
    litellm_params:
      model: stepfun-ai/step-3.5-flash
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        

  - model_name: Palmyra
    litellm_params:
      model: writer/palmyra-creative-122b
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens
        


  - model_name: Qwen 3.5
    litellm_params:
      model: qwen/qwen3.5-397b-a17b
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        
        
  - model_name: GPT OSS 120B
    litellm_params:
      model: openai/gpt-oss-120b
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

  

  - model_name: glm-5.1 nvidia
    litellm_params:
      model: nvidia_nim/z-ai/glm-5.1
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        
  - model_name: DSv4
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-pro
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens


  - model_name: DSv4 Flash
    litellm_params:
      model: deepseek-ai/deepseek-v4-flash
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens

        
  - model_name: Mistral
    litellm_params:
      model: nvidia_nim/mistralai/mistral-large-3-675b-instruct-2512
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      max_tokens: 8192
      max_completion_tokens: 8192
      additional_drop_params:
        - max_tokens
        - max_completion_tokens


  - model_name: Kimi
    litellm_params:
      model: moonshotai/kimi-k2.6
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: https://integrate.api.nvidia.com/v1
      additional_drop_params:
        - max_tokens
        - max_completion_tokens
  

litellm_settings:
  callbacks: ["remove_name_plugin.remove_name_handler_instance"]
  #set_verbose: True  # Uncomment this if you want to see verbose logs; not recommended in production
  #modify_params: True
  drop_params: True
  success_callback: ["prometheus"]
  # max_budget: 100 
  # budget_duration: 30d
  num_retries: 5
  request_timeout: 600
  telemetry: False
  context_window_fallbacks: [{"gpt-3.5-turbo": ["gpt-3.5-turbo-large"]}]
  default_team_settings: 
    - team_id: team-1
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PROJECT1_PUBLIC # Project 1
      langfuse_secret: os.environ/LANGFUSE_PROJECT1_SECRET # Project 1
    - team_id: team-2
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PROJECT2_PUBLIC # Project 2
      langfuse_secret: os.environ/LANGFUSE_PROJECT2_SECRET # Project 2
      langfuse_host: https://us.cloud.langfuse.com
  # cache: true   # [OPTIONAL] use for caching responses 
  # enable_caching_on_provider_specific_optional_params: True  # Include provider-specific params in cache keys
  # cache_params:  # And for shared health check
  #   type: redis
  #   host: localhost
  #   port: 6379

# For /fine_tuning/jobs endpoints
#finetune_settings:
  #- custom_llm_provider: azure
    #api_base: os.environ/AZURE_API_BASE
    #api_key: os.environ/AZURE_API_KEY
    #api_version: "2023-03-15-preview"
  #- custom_llm_provider: openai
    #api_key: os.environ/OPENAI_API_KEY

 #for /files endpoints
#files_settings:
  #- custom_llm_provider: azure
    #api_base: os.environ/AZURE_API_BASE
    #api_key: os.environ/AZURE_API_KEY
    #api_version: "2023-03-15-preview"
  #- custom_llm_provider: openai
    #api_key: os.environ/OPENAI_API_KEY

router_settings:
  routing_strategy: usage-based-routing-v2 
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
  enable_pre_call_checks: true
  model_group_alias: {"my-special-fake-model-alias-name": "fake-openai-endpoint-3"} 

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY # [OPTIONAL] Use to enforce auth on proxy. See - https://docs.litellm.ai/docs/proxy/virtual_keys
  store_model_in_db: True
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  database_connection_pool_limit: 10
  # background_health_checks: true
  # use_shared_health_check: true
  # health_check_interval: 30
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

  pass_through_endpoints:
    - path: "/v1/rerank"                                  # route you want to add to LiteLLM Proxy Server
      target: "https://api.cohere.com/v1/rerank"          # URL this route should forward requests to
      headers:                                            # headers to forward to this URL
        content-type: application/json                    # (Optional) Extra Headers to pass to this endpoint 
        accept: application/json
      forward_headers: True

# environment_variables:
  # settings for using redis caching
  # REDIS_HOST: redis-16337.c322.us-east-1-2.ec2.cloud.redislabs.com
  # REDIS_PORT: "16337"
  # REDIS_PASSWORD: 
